[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/vote"
  to = "/post/register-to-vote-in-the-general-election/"  

[[redirects]]
  from = "/Vote-No-1"
  to = "/post/why-you-should-vote-neasa-hourigan-number-1-on-saturday-february-8th/"  


[[redirects]]
  from = "/ph"
  to = "/post/update-on-the-plans-to-redevelop-the-phoenix-park/"  

[[redirects]]
  from = "/map"
  to = "/post/map-of-dublin-central-constituency/"  

[[redirects]]
  from = "/clinic"
  to = "https://forms.gle/SkW2k41R3fZ5BHrR9"  
