[build.environment]
  YARN_VERSION = "1.22.4"
  NPM_VERSION = "6.10.3"
  HUGO_VERSION = "0.75.1"
  NODE_VERSION = "12.18.4"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/vote"
  to = "/post/register-to-vote-in-the-general-election/"  

[[redirects]]
  from = "/Vote-No-1"
  to = "/post/why-you-should-vote-neasa-hourigan-number-1-on-saturday-february-8th/"  


[[redirects]]
  from = "/ph"
  to = "/post/update-on-the-plans-to-redevelop-the-phoenix-park/"  

[[redirects]]
  from = "/map"
  to = "/post/map-of-dublin-central-constituency/"  

[[redirects]]
  from = "/clinic"
  to = "https://forms.gle/SkW2k41R3fZ5BHrR9"  

[[redirects]]
  from = "/botanic"
  to = "https://forms.gle/G4dcUEAfLRsD1GEz9"  

[[redirects]]
  from = "/np"
  to = "/?utm_source=Northside%20People&utm_medium=banner&utm_campaign=Nov2020"

[[redirects]]
  from = "/n1020"
  to = "/?utm_source=Newsletter&utm_medium=qr&utm_campaign=NewsletterOct2020"
  
[[redirects]]
  from = "/waste"
  to = "/post/waste-action/"  

[[redirects]]
  from = "/donals-new-ringtone"
  to = "/docs/bong-bong-bong.m4a"  

[[redirects]]
  from = "/hse-supports"
  to = "https://www2.hse.ie/services/mental-health-supports-and-services-during-coronavirus/mental-health-supports-and-services-during-coronavirus.html"  
  
[[redirects]]
  from = "/wellbeing"
  to = "/post/launch-of-green-partys-position-paper-on-wellbeing-indicators/"    

[[redirects]]
  from = "/pp"
  to = "/post/holy-cross-college/"
  
[[redirects]]
  from = "/sc"
  to = "https://m.neasahourigan.com/sc"    

[[redirects]]
  from = "/scooter"
  to = "https://m.neasahourigan.com/sc"    

[[redirects]]
  from = "/scooters"
  to = "https://m.neasahourigan.com/sc"    

[[redirects]]
  from = "/grangegorman"
  to = "/post/grangegorman/"    

[[redirects]]
  from = "/Grangegorman"
  to = "/post/grangegorman/"    

[[redirects]]
  from = "/BC3"
  to = "/docs/BusConnects-third-round-of-public-consultation-Submission.pdf" 

[[redirects]]
  from = "/hendrons"
  to = "/post/public-meeting-on-280-bed-co-living-development-at-hendrons-site/"

[[redirects]]
  from = "/Dart4Cabra"
  to = "/post/dart-for-cabra/"
  
[[redirects]]
  from = "/DartSign"
  to = "https://forms.office.com/Pages/ResponsePage.aspx?id=8OxxzpcLskeWbLTsyNsj8hNdbngt8uNCnzRZ6ALOFUdUQThOVEgzWk5KQjZVVEE4NERHM0ZTQUVDVy4u" 
  
[[redirects]]
  from = "/maternal"
  to = "/post/maternal-care/"
  
[[redirects]]
  from = "/holycross"
  to = "/post/holy-cross-college/"

[[redirects]]
  from = "/cobblestone"
  to = "/post/cobblestone/"

[[redirects]]
  from = "/devplan"
  to = "/post/devplan/"
  
[[redirects]]
  from = "/ca-drugs"
  to = "https://m.neasahourigan.com/ca-drugs"  

[[redirects]]
  from = "/ca-drugs"
  to = "/docs/Citizens-Assembly-on-Drugs-Position-Paper.pdf"  

