baseurl = "https://neasahourigan.com/"
languageCode = "en-us"
title = "Neasa Hourigan T.D."

disableKinds = ["taxonomyTerm"]

googleAnalytics = "UA-135763425-1"

[markup.goldmark.renderer]
unsafe= true